const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.OnTapGestureObject
	];
};
self.C3_JsPropNameTable = [
	{escritorioggwp: 0},
	{alienGreen_walk: 0},
	{idle1d: 0},
	{alienBlue_walk: 0},
	{idle: 0},
	{playbtn: 0},
	{credits: 0},
	{Texto: 0},
	{escritorioggwp2: 0},
	{Esmaecer: 0},
	{Texto2: 0},
	{facin: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{idle2: 0},
	{escritorioggwp3: 0},
	{escritorioggwp4: 0},
	{Texto3: 0},
	{Toque: 0},
	{escritorioggwp5: 0},
	{Sólido: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Spriteidles: 0},
	{dir: 0},
	{vida: 0},
	{idle1d2: 0},
	{Sprite4: 0},
	{Sprite3: 0},
	{Texto4: 0},
	{back: 0},
	{poirta: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{placaremovebgpreview: 0},
	{colidir: 0},
	{morte: 0},
	{Sprite7: 0},
	{Projétil: 0},
	{slash: 0},
	{Mouse: 0},
	{Teclado: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{teclas: 0},
	{mouse2: 0},
	{Sprite10: 0},
	{PlanoDeFundoEmBlocos: 0},
	{CapturaDeTela: 0}
];

self.InstanceType = {
	escritorioggwp: class extends self.ISpriteInstance {},
	alienGreen_walk: class extends self.ISpriteInstance {},
	idle1d: class extends self.ISpriteInstance {},
	alienBlue_walk: class extends self.ISpriteInstance {},
	idle: class extends self.ISpriteInstance {},
	playbtn: class extends self.ISpriteInstance {},
	credits: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	escritorioggwp2: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	idle2: class extends self.ISpriteInstance {},
	escritorioggwp3: class extends self.ISpriteInstance {},
	escritorioggwp4: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Toque: class extends self.IInstance {},
	escritorioggwp5: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Spriteidles: class extends self.ISpriteInstance {},
	idle1d2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	back: class extends self.ISpriteInstance {},
	poirta: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	placaremovebgpreview: class extends self.ISpriteInstance {},
	colidir: class extends self.ISpriteInstance {},
	morte: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	slash: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	teclas: class extends self.ISpriteInstance {},
	mouse2: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	CapturaDeTela: class extends self.ISpriteInstance {}
}